// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClYoOVLy9HfIBcSZuifVePMgYR6UMfU-4',
    appId: '1:72853837199:web:01c3d22b9f0b77105fa7fa',
    messagingSenderId: '72853837199',
    projectId: 'mobileappdevelopmentproj-95531',
    authDomain: 'mobileappdevelopmentproj-95531.firebaseapp.com',
    storageBucket: 'mobileappdevelopmentproj-95531.firebasestorage.app',
    measurementId: 'G-7CHDPXWCJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoCkpNOwsZz4gJPul4i2IeqR7WIztdCI',
    appId: '1:72853837199:android:d84fb2bf8b92feec5fa7fa',
    messagingSenderId: '72853837199',
    projectId: 'mobileappdevelopmentproj-95531',
    storageBucket: 'mobileappdevelopmentproj-95531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu28BPDgigWe6zn2ssA6RuWfkyxbQjNT8',
    appId: '1:72853837199:ios:261da8e3dc142b275fa7fa',
    messagingSenderId: '72853837199',
    projectId: 'mobileappdevelopmentproj-95531',
    storageBucket: 'mobileappdevelopmentproj-95531.firebasestorage.app',
    iosBundleId: 'com.example.mindEase',
  );

}