import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:mind_ease/services/notification_service.dart';
import 'app/locator.dart';
import 'app/app.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:timezone/data/latest_all.dart' as tz;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  tz.initializeTimeZones();
  setupLocator();

  // 🔔 Start notification service
  await locator<NotificationService>().init();
  await locator<NotificationService>().scheduleDailyReminder();
  
  runApp(MindEaseApp());
}